name: Deploy Python Backend to Azure

on:
  workflow_dispatch:

env:
  APP_NAME: guardian-sphere-python
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 3. Install dependencies in a virtual environment
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt

      # 4. Debug installed packages
      - name: Verify installed packages
        run: |
          source venv/bin/activate
          pip freeze

      # 5. Create startup script and ensure it's executable
      - name: Create startup script
        run: |
          echo '#!/bin/bash' > startup.sh
          echo 'source venv/bin/activate' >> startup.sh
          echo 'python run_waitress.py' >> startup.sh
          git add startup.sh
          git update-index --chmod=+x startup.sh

      # 6. Package application
      - name: Package application
        run: |
          zip -r app.zip . -x "*.git*" "*.github*" "__pycache__/*" "*.log" "tmp/*" "*.sqlite*"

      # 7. Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PYTHON }}
          package: app.zip

      # 8. Verify deployment
      - name: Verify deployment
        run: |
          curl -I https://${{ env.APP_NAME }}.azurewebsites.net || echo "Deployment verification failed"
