name: Deploy Python Backend to Azure

on:
  workflow_dispatch:

env:
  APP_NAME: guardian-sphere-python  # Nom de votre App Service
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 3. Installer les dépendances directement sans venv
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Créer le fichier de commande de démarrage
    - name: Set startup command
      run: |
        echo 'python run_waitress.py' > startup.sh

    # 5. Préparer le package d'application
    - name: Package application
      run: |
        zip -r app.zip . -x "*.git*" "*.github*" "__pycache__/*" "*.log" "tmp/*"

    # 6. Déployer sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PYTHON }}
        package: app.zip

    # 7. Vérification du déploiement
    - name: Verify deployment
      run: |
        curl -I https://${{ env.APP_NAME }}.azurewebsites.net || echo "Deployment verification failed"
