name: Deploy Python Backend to Azure

on:
  workflow_dispatch:

env:
  APP_NAME: guardian-sphere-python  # Nouveau nom de votre App Service
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # 3. Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Préparer le package
    - name: Package application
      run: |
        zip -r app.zip . -x "*.git*" "*.github*"

    # 5. Déployer sur Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PYTHON  }}
        package: app.zip

    # 6. Vérification du déploiement
    - name: Verify deployment
      run: |
        curl -I https://${{ env.APP_NAME }}.azurewebsites.net || echo "Deployment verification failed"
